### ISSUE TITLE
Plural IDs error

### ISSUE THREAD

**Issue by dro-sh** [ldez/tagliatelle#16]
I have a struct with array of IDs.
Structure:
```go
type WithArrays struct {
  ModelIDs []string   `json:"modelsIds"`
  MembersIDs []string `json:"membersIds"`
}
```
Config:
```yaml
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
```

But linter thinks that it is a part of field name. I should disable linter for whole structure.

<img width="441" alt="Screenshot 2023-02-23 at 10 14 27 AM" src="https://user-images.githubusercontent.com/37456151/220841319-77e2cebf-9d31-437e-8d83-abb67812db7d.png">

Is there a way to fix it?
