### ISSUE TITLE
allow skipping checking for JSON in a certain package with `golangci-lint`

### ISSUE THREAD

**Issue by hhhapz** [ldez/tagliatelle#28]
`golangci-lint`'s base settings is defined as the following:
```go
cfg := tagliatelle.Config{
	Base: tagliatelle.Base{
		Rules: map[string]string{
			"json":   "camel",
			"yaml":   "camel",
			"header": "header",
		},
	},
}

```

This is a sane default, however unfortunately I am in a situation where I am creating a project that is mapping a bunch of different APIs, and they all have their own JSON case format. Would it be possible for the configuration for this project to allow me to:
1. disable checking (e.g. `"json": "none"`) as a rule
2. allow applying some override to a package and **all** of it's subpackages. (Perhaps with a `recursive: true` flag?). 

The use case for 1 is to be able to either disable json checking in the root of my repository, and only enabling it in a certain package (e.g. in my package with my application structs whose tags I want to keep consistent).

The use case for 2 is to be able to have a single package with all of my 3rd party api integrations (e.g. an `integrations` package with a subpackage for each integration), which contain structs modelling to the integration's REST API casing rules, which are inconsistent with the rest of the project, and would like to entirely just exclude `tagliatelle` for.

If this is possible already with `golangci-lint`, please do let me know!

**Comment by ldez** [comment]
It already exists

**Comment by ldez** [comment]
For the given tree:

```
.
├── go.mod
├── go.sum
├── main.go
├── cloudflare
│   ├── cloudflare.go
│   ├── api
│   │   └── api.go
│   └── web
│       └── api.go
├── linode
│   └── linode.go
└── porkbun
    └── porkbun.go
```

The configuration:

```yml
version: "2"

linters:
  enable:
    - tagliatelle
  settings:
    tagliatelle:
      case:
        rules:
          json: '' # ignore this rule
        use-field-name: true

        overrides:
          - pkg: cloudflare # this rule's override apply to the package and all its subpackages
            rules:
              json: camel
            use-field-name: true
          - pkg: linode # this rule's override apply to the package and all its subpackages
            rules:
              json: kebab
            use-field-name: true
          - pkg: porkbun # this rule's override apply to the package and all its subpackages
            rules:
              json: header
            use-field-name: true
```

Result:

```console
$ golangci-lint run
cloudflare/api/api.go:4:15: json(camel): got 'bar_field' want 'field' (tagliatelle)
        Field string `json:"bar_field"`
                     ^
cloudflare/cloudflare.go:4:15: json(camel): got 'foo_color' want 'color' (tagliatelle)
        Color string `json:"foo_color"`
                     ^
cloudflare/web/api.go:4:15: json(camel): got 'bar_field' want 'field' (tagliatelle)
        Field string `json:"bar_field"`
                     ^
linode/linode.go:4:14: json(kebab): got 'foo_name' want 'name' (tagliatelle)
        Name string `json:"foo_name"`
                    ^
porkbun/porkbun.go:4:14: json(header): got 'foo_text' want 'Text' (tagliatelle)
        Text string `json:"foo_text"`
                    ^
5 issues:
* tagliatelle: 5
```
